### PR TITLE
Bring PX4-SITL_gazebo up-to-date with the upstream repo used by the official PX4-Autopilot:stable.

### PR DESCRIPTION
**Pull request by lmarzen**
This is necessary so that the Open-UAS fork of PX4-Autopilot can be brought up-to-date without breaking.

### CODE REVIEW

**Comment by lmarzen** [comment]
Please select 'Squash and merge' when merging.

**Comment by lmarzen** [comment]
To test these changes you can checkout the updated PX4-Autopilot build that this is meant to be paired with. use "git checkout PX4-stable" then run "git submodule update --init --recursive" before testing.

**Comment by varadk2612** [comment]
Thanks Luke. I’ll give it a shot and let you know

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lmarzen** [comment]
Related pull request for PX4-Autopilot: Open-UAS/PX4-Autopilot#12

**Pull request merged**
